### ISSUE TITLE
Elasticsearch entries failing to parse/save

### ISSUE THREAD

**Issue by phutchins** [Storj/data-api#1]
When statusify sends a report to mongo and elasticsearch, it is not saved in elasticsearch and errors. The error is as follows...

```
2016-05-27T22:07:48.174Z - debug: Saved report in mongo
2016-05-27T22:07:48.174Z - debug: Found elasticsearch instance for model: elasticsearch
2016-05-27T22:07:48.174Z - debug: Creating in ElasticSearch... _bsontype=ObjectID, id=WHÅ4£­JNª
2016-05-27T22:07:48.174Z - debug: ElasticSearch: starting request {"method":"POST","path":"/data-api/report/5748c534a3ad4a1100964eaa","body":{"__v":0,"requestID":"8c8a70a9691aae1e9fdeb50a369ae2ca","payment":"Am5IS8GYd0RxxndYORj6wrym5EttpAUl+h7yfOyqfZ4p1Ccq4p+KJ/idYadDrUxl9LrQbYZxYIEk7ARct2190HTDztSn1xnlxaMLGEuQYipwNbVdO9ea910tldziSoRR+Wb+fIEOqirk5Yic95EcWv27DRSPWvddUi7qxiY6CxEb","timestamp":"2016-05-27T22:07:46.883Z","signature":"H35eXMpwcCG1ua+yaPcAYF1wjfzk4YBwv32UKCK/HUrHAlTBAAxEBzYZlSFPfe7gpWryil2JwhK9X1bA8+yGqxE=","_id":"5748c534a3ad4a1100964eaa","contact":{"protocol":"0.6.16","address":"104.196.135.20","port":8525,"nodeID":"d99bb49a26b3908a974112e287e42634a30dc677"},"bandwidth":{"upload":1.44,"download":1.79},"storage":{"free":2147482900,"used":748}},"query":{"op_type":"create"}}
2016-05-27T22:07:48.217Z - debug: ElasticSearch: Request complete
2016-05-27T22:07:48.218Z - warn: [8c8a70a9691aae1e9fdeb50a369ae2ca] method: report.put error: [mapper_parsing_exception] failed to parse Error: [mapper_parsing_exception] failed to parse
    at respond (/usr/src/app/node_modules/elasticsearch/src/lib/transport.js:289:15)
    at checkRespForFailure (/usr/src/app/node_modules/elasticsearch/src/lib/transport.js:248:7)
    at HttpConnector.<anonymous> (/usr/src/app/node_modules/elasticsearch/src/lib/connectors/http.js:164:7)
    at IncomingMessage.wrapper (/usr/src/app/node_modules/elasticsearch/node_modules/lodash/index.js:3095:19)
    at emitNone (events.js:85:20)
    at IncomingMessage.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:913:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)"
2016-05-27T22:07:48.219Z - info: [8c8a70a9691aae1e9fdeb50a369ae2ca] method: report.put durationMs=107
2016-05-27T22:12:48.100Z - info: [7084c0a016d2d892c9ebb0c2373c056e] method: report.put client: 32284b2746f4d5665c51aa83ef230369123749b1
```

It looks like this may be due to one of the breaking changes in ES 2.0+

https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_20_mapping_changes.html#migration-meta-fields

**Comment by niahmiah** [comment]
It could also be that the mapping it generated doesn't match the new document. I'll need to create a mongo schema to Es mapping converter to solve that.

Otherwise, this is using the official ES driver, and you can set the protocol version, so I don't think we'll have compatibility issues. It would be odd for them not to support their own product releases.

~Ian Patton

**Comment by phutchins** [comment]
I confirmed that we're using the latest version of the elasticsearch node module (11.0.1) which defaults to apiVersion 2.3. I'm using ES 2.3. I also added it to my config and set it to 2.3 to be sure… 

I think creating the mapping should solve the issue.

**Comment by phutchins** [comment]
Found that the issue was that we were pushing the _id field in the data to ES which does not work in current versions. I deleted this from the data and left it in the request portion which resolved the issue.
